import { Playfair_Display, } from "next/font/google";
import Sidebar from "./components/sidebar";
import "./globals.css";



const inter = Playfair_Display({ subsets: ["latin"] });

export const metadata = {
  title: "Kashif Nawaz - Software Engineer",
  description: "Generated by Kashif Nawaz- Full Stack Developer",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
      ></link>
   
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossOrigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossOrigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossOrigin="anonymous"></script>
    </head>

      <body className={inter.className}>
        <div className="container-fluid h-100">
          <div className="row h-100">
            <div className="col-sm-12 -col-md-12 col-lg-4">
              <Sidebar />
            </div>
            <div className="col-sm-12 -col-md-12 col-lg-8"> {children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
